version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  assignees:
  - freemanjp
  ignore:
  - dependency-name: com.h3xstream.findsecbugs:findsecbugs-plugin
    versions:
    - "> LATEST"
