dist: xenial

language: java

jdk: openjdk8

before_cache:
- rm --force --recursive --verbose $HOME/.m2/repository/com/github/gantsign

cache:
  directories:
  - $HOME/.m2

install: true

jobs:
  include:
  - stage: Test
    script: .travis/test.sh

  - stage: Deploy
    script: .travis/deploy.sh
    if: type = push AND (tag IS present OR branch = master)

branches:
  only:
  - master
  - /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)([\.\-].*)?$/
